accounts/urls.py
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name="login"),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
    url(r"profile/$", views.Profile.as_view(), name="profile"),
    url(r"password_reset/$",
         auth_views.PasswordResetView.as_view(
             template_name="accounts/password_reset.html"
         ),
         name="password_reset"),
    url(r"password_reset/done/$",
         auth_views.PasswordResetDoneView.as_view(
             template_name="accounts/password_reset_done.html"
         ),
         name="password_reset_done"),
    url(r"reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
         auth_views.PasswordResetConfirmView.as_view(
             template_name="accounts/password_reset_confirm.html"
         ),
         name="password_reset_confirm"),
    url(r"reset/done/$",
         auth_views.PasswordResetCompleteView.as_view(
             template_name="accounts/password_reset_complete.html"
         ),
         name="password_reset_complete"),
]

posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
    url(r"update/(?P<pk>\d+)/$",views.UpdatePost.as_view(),name="update"),
]

simplesocial/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include('django.contrib.auth.urls')),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib import auth
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model

def get_profile_image_filepath(self, filename):
    return f'profile_pics'

def get_default_profile_image():
    return "Groupwork-website.jpg"

class User(auth.models.User, auth.models.PermissionsMixin):
  
    def __str__(self):
        return "@{}".format(self.username)



class UserProfile(models.Model):

    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    profile_image = models.ImageField(upload_to=get_profile_image_filepath, default=get_default_profile_image)

    def get_profile_image_filename(self):
        return f'{self.user.username} Profile'

    

    
    

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from . import models
from django import forms


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'last_name', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = models.UserProfile
        fields = ['profile_image']

accounts/views.py
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView, View
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages

from .forms import UserUpdateForm, ProfileUpdateForm, UserCreateForm

class SignUp(CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"


class Profile(View): 
    def post( self, request, *args, **kwargs):
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.userprofile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('accounts:profile')
    

    def get( self, request, *args, **kwargs):
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.userprofile)
        context = {
            'u_form': u_form,
            'p_form': p_form
        }
        return render(request, 'accounts/profile.html', context)

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="pre-content nav-d">
    <h1 class="form-text page-header">Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="my-btn">
        <a href="{% url 'accounts:password_reset' %}" class="btn btn-simple">Forgot Password?</a>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="pre-content nav-d">
    <h1 class="page-header">Password Reset</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Request Password Reset" class="my-btn">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %}
{% block content %}
<div class="alert alert-info pre-content nav-d" role="success">Password reset successsful!</div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="pre-content nav-d">
    <h1 class="page-header">Password Reset</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Reset Password" class="my-btn">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends "base.html" %}
{% block content %}
<div class="alert alert-info pre-content nav-d" role="alert">An email has been sent with instructions to reset your password!</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

<div class="pre-content nav-d">
      <div class="media">
        <img class="img-circle img-responsive account-img" alt="Responsive image" src="{{ user.userprofile.profile_image.url }}" max-width="auto" height="auto">
        <div class="media-body">
          <h2 class="account-heading page-header">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
     <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form p_form %}
        {% bootstrap_form u_form %}
        <input type="submit" value="Update" class="ny-btn">
    </form>
    </div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Sign Up" class="btn btn-default">
    </form>
</div>
{% endblock %}