accounts/urls.py
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name="login"),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
    url(r"profile/$", views.Profile.as_view(), name="profile"),
    url(r"password_reset/$",
         auth_views.PasswordResetView.as_view(
             template_name="accounts/password_reset.html"
         ),
         name="password_reset"),
    url(r"password_reset/done/$",
         auth_views.PasswordResetDoneView.as_view(
             template_name="accounts/password_reset_done.html"
         ),
         name="password_reset_done"),
    url(r"reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
         auth_views.PasswordResetConfirmView.as_view(
             template_name="accounts/password_reset_confirm.html"
         ),
         name="password_reset_confirm"),
    url(r"reset/done/$",
         auth_views.PasswordResetCompleteView.as_view(
             template_name="accounts/password_reset_complete.html"
         ),
         name="password_reset_complete"),
]

groups/urls.py
from django.conf.urls import url

from . import views

app_name = 'groups'

urlpatterns = [
    url(r"^$", views.ListGroups.as_view(), name="all"),
    url(r"^user_groups/$", views.UserGroups.as_view(), name="user_group"),
    url(r"^new/$", views.CreateGroup.as_view(), name="create"),
    url(r"^posts/in/(?P<slug>[-\w]+)/$",views.SingleGroup.as_view(),name="single"),
    url(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    url(r"leave/(?P<slug>[-\w]+)/$",views.LeaveGroup.as_view(),name="leave"),
]

posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
    url(r"update/(?P<pk>\d+)/$",views.UpdatePost.as_view(),name="update"),
]

simplesocial/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include('django.contrib.auth.urls')),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>BV Social</title>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

    <link href="<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">

  </head>

  <body class="container-footer">
  
    <nav class="navbar  mynav" role="navigation" id="navbar">
    	<div class="container">
        <a class="navbar-brand mynav" href="{% url 'home' %}">BVSocial</a>
          <ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <li><a href="{% url 'accounts:profile' %}" class="btn btn-simple">Profile</a></li>
                      <li><a href="{% url 'posts:create' %}" class="btn btn-simple">Post</a></li>
                      <li><a href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                      <li><a href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a></li>
                      <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
    						{% else %}
    						      <li><a href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
    						      <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
    						{% endif %}
          </ul>
      </div>
    </nav>

    <div class=" mycontent">
        {% block content %}

        {% endblock %}
    </div>

    <footer>
      &copy copyright BVSocial
      <a href="{% url 'admin:index' %}" class="admin">Admin</a>
    </footer>
  
    <canvas id="canvas"></canvas>

  </body>

  <script type="text/javascript" src="{% static 'simplesocial/js/master.js' %}"> </script>

</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<div class="flex-1">
<div id="carousel-example-generic slider" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
   <div class="carousel-inner" role="listbox">

      <div class="item active">
        <img src="{% static 'images\Groupwork-website.jpg' %}">
      </div>

      <div class="item">
        <img src="{% static 'images\groupwork.jpg' %}">  
      </div>

      <div class="item">
        <img src="{% static 'images\Interview-Follow-Up.png' %}">  
      </div>

  </div>
  <!-- Controls -->
 <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>	
    <center>
    <div class="jumbotron">
    <h1>Welcome to BVSocial!</h1>
    <h2>The best community to create groups and talk for students!</h2>
    {% if user.is_authenticated == False %}
         <h2><a href="{% url 'accounts:login' %}">Login</a> or <a href="{% url 'accounts:signup' %}">Sign-up</a> for free to get started!</h2>
  	{% endif %}
    </div>
   </center>
  </div>

{% endblock %}


   

templates/test.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container-2">

  
<div class="flex-1">
<div id="carousel-example-generic slider" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
   <div class="carousel-inner" role="listbox">

      <div class="item active">
        <img src="{% static 'images\Groupwork-website.jpg' %}">
      </div>

      <div class="item">
        <img src="{% static 'images\groupwork.jpg' %}">  
      </div>

      <div class="item">
        <img src="{% static 'images\Interview-Follow-Up.png' %}">  
      </div>

  </div>
  <!-- Controls -->
 <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<center>
<div class="jumb-home">
<div class="jumbotron">
  <h1>Welcome to BV Social!</h1>

  <h2><a href="{% url 'groups:all'%}" class="btn btn-primary btn-large"> Go to all Groups</a></h2>
  <h2><a href="{% url 'groups:user_group'%}" class="btn btn-primary btn-large">Go to favourites</a></h2>
</div>
</div>
</center>
</div>

{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
<center>
<h1>Thank You for visiting!</h1>
 {% if user.is_authenticated == False %}
         <h2><a href="{% url 'accounts:login' %}">Login</a> or <a href="{% url 'accounts:signup' %}">Sign-up</a> for free to get started!</h2>
  	{% endif %}
</center>
</div>
{% endblock %}